console.log("Testing strings equality");
console.log("apple" == "apple");
console.log("Apple" == "apple");
console.log("Apple".toLowerCase() == "apple");
console.log("Numerical Test");
console.log(120 > 50);
console.log(15 < 1);
var fruit = ["Apple", "Banana", "Mango"];
console.log("Is 'apple' in fruits?");
console.log(fruit.includes("Apple"));
console.log(!fruit.includes("Cherry"));
