var car0 = "Austin Martin";
console.log("You have 'Austin Martin', and I predict True.");
console.log(car0 == "Austin Martin");
var car1 = "BMW";
console.log("You have 'BMW', and I predict True.");
console.log(car1 == "BMW");
var car2 = "Rolls Royce";
console.log("You have 'Rolls Royce', and I predict True.");
console.log(car2 == "Rolls Royce");
var car3 = "Audi";
console.log("You have 'Audi', and I predict True.");
console.log(car3 == "Audi");
;
var car4 = "Bugatti";
console.log("You have 'Bugatti', and I predict True.");
console.log(car4 == "Bugatti");
var car5 = "Toyota";
console.log("You have 'Austin Martin', and I predict True.");
console.log(car5 == "Austin Martin");
var car6 = "Honda";
console.log("You have 'BMW', and I predict True.");
console.log(car6 == "BMW");
var car7 = "Subaru";
console.log("You have 'Rolls Royce', and I predict True.");
console.log(car7 == "Rolls Royce");
var car8 = "Suzuki";
console.log("You have 'Audi', and I predict True.");
console.log(car8 == "Audi");
;
var car9 = "Mitsubhishi";
console.log("You have 'Bugatti', and I predict True.");
console.log(car9 == "Bugatti");
